name: docker cd
on: workflow_dispatch

jobs:
  docker-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: get pem file
        run: |
          echo "${{ secrets.secretfile }}" > key.pem
          chmod 400 key.pem
  
      - name: Push Image
        run: ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.201.229.181 "cd /home/ec2-user && sudo yum install docker -y && echo '${{ vars.DOCKER_PASSWORD }}' | sudo docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin && sudo docker pull ${{ vars.DOCKER_USERNAME }}/myapp:latest && sudo docker run -d -p 80:5001 myapp" 
